version: 2

jobs:
  detect-changes:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Determine which packages have changed
          command: |
            yarn 
            yarn bootstrap
            yarn start:ci

workflows:
  version: 2
  build:
    jobs:
      - detect-changes
      