version: 2

jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: ~/repo
    environment:
      O: benjlevesque
      R: monorepo-test
    steps:
      - checkout
      - run:
          name: Determine which directories have changed
          command: |
            git diff --no-commit-id --name-only -r `git log -n 2 --oneline --pretty=format:"%h" | tail -n1` | cut -d/ -f2 | sort -u >  projects
            printf "Modified directories:\n"
            cat projects
            find ./packages/*/package.json -maxdepth 2 -type f | xargs -l1 dirname | xargs -l1 basename > package_list
            printf "Available packages:\n"
            cat package_list
            while read project; do
              if grep -Fxq $project package_list; then
                printf "\nTriggerring build for dir:"$project 
                curl -s -u ${CIRCLE_TOKEN}: --request POST --form "config=@.circleci/$project.yml" https://circleci.com/api/v1.1/project/github/$O/$R/tree/$CIRCLE_BRANCH
                # TODO can be improved with https://circleci.com/docs/api/v1-reference/#new-project-build when build_parameters are available (not yet as of 21/11/2018)
              fi
            done <projects
