version: 2

jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: ~/repo
    environment:
      O: benjlevesque
      R: monorepo-test
    steps:
      - checkout
      - run:
          name: Determine which directories have changed
          command: bash .circleci/check_changes.sh
